modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="rhodonite" #mandatory
version="1.15.2-1.0.0" #mandatory
displayName="Rhodonite" #mandatory
description='''
Rhodonite!!!
'''