modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="rhodonite" #mandatory
version="1.14.4-1.1" #mandatory
displayName="Rhodonite" #mandatory
description='''
Rhodonite!!!
'''