modLoader="javafml" #mandatory
loaderVersion="[32.0,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="rhodonite" #mandatory
version="1.16.1-1.0.3" #mandatory
displayName="Rhodonite" #mandatory
description='''
Rhodonite!!!
'''