modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
credits="vincentmet" #optional
[[mods]] #mandatory
modId="rhodonite" #mandatory
version="1.14.4-0.3" #mandatory
displayName="Rhodonite" #mandatory
description='''
Rhodonite!!!
'''