modLoader="javafml" #mandatory
loaderVersion="[36.0,)" #mandatory
license="All Rights Reserved"
credits="vincentmet" #optional
[[mods]] #mandatory
modId="rhodonite" #mandatory
version="1.16.5-1.0.0" #mandatory
displayName="Rhodonite" #mandatory
description='''
Rhodonite!!!
'''